### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by mubeenpatel99** [arish14/Android-Game-Tic-tac-toe#1]
Hey dev,
As you can see the files.you have uploaded are not complete you are missing two very important files in which the whole project of yours is dependent,
### MISSING DIRECTORIES
* app
* Gradle/wrapper
* .idea
### Drawback
Your whole projects work and the code lives in the app directory and if that is not included then your project won't work!
Resolve it as soon as possible!
Thank you!
Happy contributing.

**Comment by arish14** [comment]
Thank you for the reporting the issue, due to some technical issues they were not uploaded.
But now it is fixed and the issue is fixed.
